name: Nightly Nation Aggregation

on:
  schedule:
    - cron: '0 1 * * *'   # Runs every night at 01:00 UTC
  workflow_dispatch:      # Allows manual run from GitHub UI

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # Required so we can push

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run Aggregator
        run: dotnet run --configuration Release --no-build

      # Commiting and pushing the json to main
      - name: Commit and push generated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/stored/*.json
          git commit -m "Nightly data update" || echo "No changes to commit"
          git push
